package controller;
/**
 * THIS CLASS IS DEPRECATED AND IS NOT USED IN THE PRODUCT.
 * WE CHOSE TO KEEP THE CLASSES WE DO NOT USE FOR THEIR VALUE
 * AS ARTEFACTS.
 * THEREFORE, THIS CLASS IS NOT INCLUDED IN THE CLASS DIAGRAM
 */
public class PersonalView {
}
